/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function LogoFour(props) {
  const { nodes, materials } = useGLTF("models/logo-04.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve002.geometry}
        material={materials["Material.002"]}
        rotation={[1.462, 0, 0]}
        scale={30}
      />
    </group>
  );
}

useGLTF.preload("models/logo-04.glb");
