/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/logo-05.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve002.geometry}
        material={materials["Material.007"]}
        rotation={[1.525, 0, 0]}
        scale={54.316}
      />
    </group>
  );
}

useGLTF.preload("/logo-05.glb");
