/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function LogoOne({
  roughness = 0.4, // default roughness
  metalness = 0.6, // default metalness
  ...props // position, rotation, scale, etc.
}) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("models/logo-1.glb");
  useAnimations(animations, group);

  // Clone the material so that changing roughness/metalness
  // doesn't affect other meshes that might share it.
  const clonedMaterial = useMemo(() => {
    const mat = materials["Material.001"].clone();
    mat.roughness = roughness;
    mat.metalness = metalness;
    return mat;
  }, [materials, roughness, metalness]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Curve002"
          castShadow
          receiveShadow
          geometry={nodes.Curve002.geometry}
          material={clonedMaterial}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/logo-1.glb");
