/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Acrylic(props) {
	const { nodes, materials } = useGLTF("models/Acrylic.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane020.geometry}
				material={materials.Glass}
				position={[-15.05, 0.189, 0.016]}
				rotation={[-Math.PI / 2, 1.191, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane021.geometry}
				material={materials.Glass}
				position={[-15.084, 0.454, -0.073]}
				rotation={[-Math.PI / 2, 1.484, 0]}
			/>
		</group>
	);
}

useGLTF.preload("models/Acrylic.glb");
