/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Bamboo(props) {
	const { nodes, materials } = useGLTF("models/bamboo.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.mesh_2.geometry}
				material={materials.leafGreen}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder001_1.geometry}
				material={materials["Bamboo Stalk Surface"]}
				position={[-32.883, 0.423, 0.311]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder001_2.geometry}
				material={materials.Material}
				position={[-32.883, 0.423, 0.311]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder003.geometry}
				material={materials["Wood light"]}
				position={[-32.95, 0.198, -0.091]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder004.geometry}
				material={materials["Vibrant Green Moss"]}
				position={[-32.952, 0.158, -0.089]}
				scale={0.979}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane002.geometry}
				material={materials.leafGreen}
				position={[-33.541, 0.499, -0.39]}
				rotation={[-0.06, -0.398, 0.326]}
				scale={[0.845, 0.845, 0.057]}
			/>
		</group>
	);
}

useGLTF.preload("models/bamboo.glb");
