/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function ConventionalCotton(props) {
	const { nodes, materials } = useGLTF("models/ConventionalCotton.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.mesh_3.geometry}
				material={materials["leafGreen.002"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.mesh_6.geometry}
				material={materials["Material.003"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder023.geometry}
				material={materials["Hexagonal Metal Frames Blueish"]}
				position={[-46.275, 0.104, -0.006]}
				scale={1.152}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Retopo_Sphere015.geometry}
				material={materials["Cotton pad muji.001"]}
				position={[-45.697, 1.455, -0.222]}
				rotation={[0.59, -1.1, 0.407]}
				scale={5.497}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Retopo_Sphere019.geometry}
				material={materials["Cotton pad muji.001"]}
				position={[-45.8, 1.359, 0.466]}
				rotation={[2.992, -0.805, 2.931]}
				scale={5.497}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder022.geometry}
				material={materials["Muddy Soil Gravel.001"]}
				position={[-46.196, 0.832, 0.051]}
				rotation={[0.139, 0, 0]}
				scale={[0.35, 0.18, 0.35]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder024.geometry}
				material={materials["Bamboo.001"]}
				position={[-46.228, 0.503, 0]}
				scale={[0.05, 0.36, 0.05]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Retopo_Landscape002.geometry}
				material={materials["Black Concave Circles"]}
				position={[-46.29, 0.316, -0.094]}
				scale={[0.907, 0.52, 0.907]}
			/>
		</group>
	);
}

useGLTF.preload("models/ConventionalCotton.glb");

rembrandt;

city;
