/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Nylon(props) {
	const { nodes, materials } = useGLTF("models/Nylon.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder014.geometry}
				material={materials["Satin Fabric"]}
				position={[-1.03, 1.514, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane051.geometry}
				material={materials["Snooker Pool Table Cloth"]}
				position={[-2.338, 1.497, 0]}
				rotation={[0, 0, -Math.PI / 2]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder015.geometry}
				material={materials["Neutral Woven Fabric"]}
				position={[-1.03, 1.472, 0.994]}
				rotation={[Math.PI / 2, -0.527, 0]}
				scale={0.748}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder017.geometry}
				material={materials["Neutral Woven Fabric"]}
				position={[-1.862, 2.776, 0.712]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={[0.364, 0.411, 0.444]}
			/>
		</group>
	);
}

useGLTF.preload("models/Nylon.glb");

rembrandt;

city;
