/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function OrganicCotton(props) {
	const { nodes, materials } = useGLTF("models/organicCotton.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.mesh_1.geometry}
				material={materials["leafGreen.002"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Retopo_Sphere005.geometry}
				material={materials["Cotton pad muji.001"]}
				position={[-38.929, 2.775, -0.32]}
				rotation={[1.239, -1.1, 0.407]}
				scale={5.497}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Retopo_Sphere002.geometry}
				material={materials["Cotton pad muji.001"]}
				position={[-39.031, 2.282, 0.169]}
				rotation={[-2.641, -0.805, 2.931]}
				scale={5.497}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Retopo_hand002.geometry}
				material={materials["Floral Fabric.003"]}
				position={[-39.456, 0.126, 0.034]}
				scale={0.433}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder008.geometry}
				material={materials["Muddy Soil Gravel.001"]}
				position={[-39.428, 2.114, -0.479]}
				rotation={[0.789, 0, 0]}
				scale={[0.35, 0.18, 0.35]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Retopo_NurbsPath002.geometry}
				material={materials["Clean chrome"]}
				position={[-39.423, 2.126, 1.353]}
				rotation={[0, -Math.PI / 2, 0]}
			/>
		</group>
	);
}

useGLTF.preload("models/organicCotton.glb");

rembrandt;

city;
