/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function OrganicHemp(props) {
	const { nodes, materials } = useGLTF("models/OrganicHemp.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.mesh_1.geometry}
				material={materials["Material.004"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder018.geometry}
				material={materials["Wood light"]}
				position={[10.312, 0.214, -0.155]}
				scale={[0.589, 1.656, 0.589]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.NurbsPath.geometry}
				material={materials["Bamboo Stalk Surface"]}
				position={[10.312, 0.876, -0.128]}
				rotation={[0, 0, -Math.PI / 2]}
				scale={[0.352, 1, 1]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane082.geometry}
				material={materials["Material.004"]}
				position={[10.313, 2.041, -0.128]}
				rotation={[Math.PI / 2, 0, -Math.PI]}
				scale={0.462}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder019.geometry}
				material={materials["Clay Soil"]}
				position={[10.322, 0.04, -0.144]}
				scale={0.573}
			/>
		</group>
	);
}

useGLTF.preload("models/OrganicHemp.glb");
