/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Polyester(props) {
	const { nodes, materials } = useGLTF("models/Polyester.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder005.geometry}
				material={materials["Metal Vent Slats"]}
				position={[-21.223, 1.514, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Sphere.geometry}
				material={materials.Fabric}
				position={[-22.354, 2.277, -0.005]}
				scale={0.096}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane.geometry}
				material={materials["Brushed metal"]}
				position={[-22.531, 1.517, 0]}
				rotation={[0, 0, -Math.PI / 2]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Sphere003.geometry}
				material={materials.Fabric}
				position={[-20.105, 0.784, 0]}
				scale={0.096}
			/>
		</group>
	);
}

useGLTF.preload("models/Polyester.glb");
