/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function RecycledCotton(props) {
	const { nodes, materials } = useGLTF("models/RecycledCotton.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube003.geometry}
				material={materials["Plain Duckegg Texture"]}
				position={[15.647, 0.072, 0.013]}
				rotation={[0, 0, 0.307]}
				scale={[1.44, 1.44, 0.199]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube001.geometry}
				material={materials["Plain Grey Sheer"]}
				position={[15.964, 0.093, 0.013]}
				rotation={[0, 0.263, 0.305]}
				scale={[1.44, 1.44, 0.199]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube002.geometry}
				material={materials["Floral Natural Jacquard"]}
				position={[16.235, 0.102, 0.013]}
				rotation={[0, 0.529, 0.305]}
				scale={[1.44, 1.44, 0.199]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube004.geometry}
				material={materials["Plain Gold Texture"]}
				position={[16.53, 0.12, 0.013]}
				rotation={[0, 0.824, 0.305]}
				scale={[1.44, 1.44, 0.199]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube005.geometry}
				material={materials["Red diamond fabric"]}
				position={[16.82, 0.132, 0.013]}
				rotation={[0, 1.15, 0.305]}
				scale={[1.44, 1.44, 0.199]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube.geometry}
				material={materials.recycle}
				position={[16.672, 0.363, -0.589]}
				scale={[1.106, 0.411, 1.106]}
			/>
		</group>
	);
}

useGLTF.preload("models/RecycledCotton.glb");
