/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
	const { nodes, materials } = useGLTF("models/RecycledPolyester.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube013.geometry}
				material={materials["Plain Green Texture"]}
				position={[29.684, 0.094, 0.013]}
				rotation={[0, 0, 0.307]}
				scale={[1.44, 1.44, 0.199]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube014.geometry}
				material={materials["Stripe Blue Dimout"]}
				position={[30, 0.114, 0.013]}
				rotation={[0, 0.263, 0.305]}
				scale={[1.44, 1.44, 0.199]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube015.geometry}
				material={materials["Stripe Green Dimout"]}
				position={[30.272, 0.124, 0.013]}
				rotation={[0, 0.529, 0.305]}
				scale={[1.44, 1.44, 0.199]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube016.geometry}
				material={materials["Plain Blue Texture"]}
				position={[30.567, 0.141, 0.013]}
				rotation={[0, 0.824, 0.305]}
				scale={[1.44, 1.44, 0.199]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube017.geometry}
				material={materials["Plain Black Texture"]}
				position={[30.857, 0.154, 0.013]}
				rotation={[0, 1.15, 0.305]}
				scale={[1.44, 1.44, 0.199]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube018.geometry}
				material={materials["Plain Brown Texture"]}
				position={[30.992, 0.037, -0.108]}
				rotation={[0, 1.38, 0.347]}
				scale={[1.44, 1.44, 0.199]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube020.geometry}
				material={materials.recycle}
				position={[30.705, 0.363, -0.589]}
				scale={[1.106, 0.411, 1.106]}
			/>
		</group>
	);
}

useGLTF.preload("models/RecycledPolyester.glb");
