/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function RecycledNylon(props) {
	const { nodes, materials } = useGLTF("models/RecycledNylon.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube006.geometry}
				material={materials["Snooker Pool Table Cloth"]}
				position={[22.554, 0.094, 0.013]}
				rotation={[0, 0, 0.307]}
				scale={[1.44, 1.44, 0.199]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube007.geometry}
				material={materials["Fabric Cortadito Raven"]}
				position={[22.87, 0.114, 0.013]}
				rotation={[0, 0.263, 0.305]}
				scale={[1.44, 1.44, 0.199]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube008.geometry}
				material={materials["Plain Pink Texture"]}
				position={[23.141, 0.124, 0.013]}
				rotation={[0, 0.529, 0.305]}
				scale={[1.44, 1.44, 0.199]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube009.geometry}
				material={materials["Plain Brown Flat"]}
				position={[23.436, 0.141, 0.013]}
				rotation={[0, 0.824, 0.305]}
				scale={[1.44, 1.44, 0.199]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube010.geometry}
				material={materials["Plain Red Texture"]}
				position={[23.726, 0.154, 0.013]}
				rotation={[0, 1.15, 0.305]}
				scale={[1.44, 1.44, 0.199]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube011.geometry}
				material={materials["Plain Green Flat"]}
				position={[23.861, 0.037, -0.108]}
				rotation={[0, 1.38, 0.347]}
				scale={[1.44, 1.44, 0.199]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube012.geometry}
				material={materials["Plain Purple Flat"]}
				position={[23.917, 0.017, -0.206]}
				rotation={[2.851, 1.415, -2.492]}
				scale={[1.44, 1.44, 0.199]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube019.geometry}
				material={materials.recycle}
				position={[23.582, 0.363, -0.589]}
				scale={[1.106, 0.411, 1.106]}
			/>
		</group>
	);
}

useGLTF.preload("models/RecycledNylon.glb");
