/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Silk(props) {
	const { nodes, materials } = useGLTF("models/silk.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.mesh_3.geometry}
				material={materials["Cotton pad muji.001"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.mesh019.geometry}
				material={materials["Fabric 27"]}
				position={[38.301, 0.06, -0.672]}
				rotation={[0, Math.PI / 2, 0]}
				scale={0.708}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.mesh019_1.geometry}
				material={materials["Satin Fabric"]}
				position={[38.301, 0.06, -0.672]}
				rotation={[0, Math.PI / 2, 0]}
				scale={0.708}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Retopo_WrapMaster001.geometry}
				material={materials["Red dot fabric"]}
				position={[38.291, 0.333, -0.698]}
				rotation={[1.364, 0, 0]}
				scale={3.417}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder021.geometry}
				material={materials["Floral Fabric"]}
				position={[38.341, -0.062, -0.668]}
				scale={[1.794, 0.023, 1.794]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane103.geometry}
				material={materials["Fabric.001"]}
				position={[38.411, 0.49, 0.662]}
				rotation={[0, -0.584, -1.303]}
				scale={0.9}
			/>
		</group>
	);
}

useGLTF.preload("models/silk.glb");
