/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Wool(props) {
	const { nodes, materials } = useGLTF("models/Wool.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.mesh001.geometry}
				material={materials.Fur}
				position={[-26.883, 2.628, 1.465]}
				scale={0.303}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.mesh001_1.geometry}
				material={materials["Material.002"]}
				position={[-26.883, 2.628, 1.465]}
				scale={0.303}
			/>
		</group>
	);
}

useGLTF.preload("models/Wool.glb");
