/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Earthy(props) {
	const group = useRef();
	const { nodes, materials } = useGLTF(
		"/models/earthyboundNomad_compressed.glb",
		(loader) => {
			const dracoLoader = new DRACOLoader();
			// Use the Google-hosted Draco decoder files (or change this to your local path)
			dracoLoader.setDecoderPath("https://www.gstatic.com/draco/v1/decoders/");
			loader.setDRACOLoader(dracoLoader);
		}
	);
	return (
		<group ref={group} {...props} dispose={null}>
			<mesh
				geometry={nodes.Sphere020.geometry}
				material={materials["Silver fabric procedural.001"]}
				position={[0.05, 10.61, -0.44]}
				scale={0.23}
			/>
			<mesh
				geometry={nodes.Retopo_NurbsPath070.geometry}
				material={materials["Floor rug carpet stroke pattren"]}
				position={[0.02, 10.92, 0.17]}
				rotation={[0.23, 0, 0]}
				scale={0.26}
			/>
			<mesh
				geometry={nodes.Retopo_hair001.geometry}
				material={nodes.Retopo_hair001.material}
				position={[0.04, 10.92, -0.23]}
				scale={[0.56, 0.46, 0.46]}
			/>
			<mesh
				geometry={nodes.Retopo_Cube101.geometry}
				material={nodes.Retopo_Cube101.material}
				position={[1.35, 8.63, -0.58]}
				scale={0.26}
			/>
			<mesh
				geometry={nodes.Retopo_Cube098.geometry}
				material={materials["Material.019"]}
				position={[0.05, 10.41, -0.23]}
				scale={0.23}
			/>
			<mesh
				geometry={nodes.Retopo_Cube097.geometry}
				material={nodes.Retopo_Cube097.material}
				position={[0.05, 10.4, -0.23]}
				scale={0.23}
			/>
			<mesh
				geometry={nodes.Retopo_Cube096.geometry}
				material={nodes.Retopo_Cube096.material}
				position={[0.04, 10.42, -0.39]}
				rotation={[0.51, 0, 0]}
				scale={[0.23, 0.23, 0.23]}
			/>
			<mesh
				geometry={nodes.Retopo_Cube095.geometry}
				material={nodes.Retopo_Cube095.material}
				position={[0.04, 10.39, 0.14]}
				scale={0.23}
			/>
			<mesh
				geometry={nodes.Retopo_Cube094.geometry}
				material={nodes.Retopo_Cube094.material}
				position={[0.04, 10.4, 0.13]}
				scale={0.23}
			/>
			<mesh
				geometry={nodes.Retopo_Cube093.geometry}
				material={nodes.Retopo_Cube093.material}
				position={[0.04, 10.4, 0.12]}
				scale={0.23}
			/>
			<mesh
				geometry={nodes.Retopo_body004.geometry}
				material={nodes.Retopo_body004.material}
				position={[0.04, 8.99, -0.11]}
				scale={0.26}
			/>
			<mesh
				geometry={nodes.Plane042.geometry}
				material={materials["Procedural Worn Fabric"]}
				position={[0.04, 8.75, 0.55]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.86}
			/>
			<mesh
				geometry={nodes.Plane016.geometry}
				material={materials["Material.020"]}
				position={[0.05, 10.53, -0.87]}
				rotation={[1.47, 0, Math.PI]}
				scale={[0.1, 0.1, 0.1]}
			/>
			<mesh
				geometry={nodes.Cylinder079.geometry}
				material={nodes.Cylinder079.material}
				position={[-0.16, 10.96, -0.52]}
				rotation={[-2.85, 0.68, -0.81]}
				scale={[-0.1, -0.1, -0.1]}
			/>
			<mesh
				geometry={nodes.Cylinder066.geometry}
				material={materials["Material.022"]}
				position={[0.04, 10.45, -0.23]}
				rotation={[0, 0, -Math.PI / 2]}
				scale={0.23}
			/>
			<group position={[-0.01, 0.26, 0.47]} rotation={[Math.PI / 2, 0, 0]}>
				<mesh
					geometry={nodes.bomberJacket001_1.geometry}
					material={materials["Gray Carpet (Procedural)"]}
				/>
				<mesh
					geometry={nodes.bomberJacket001_2.geometry}
					material={materials["Carpet - Off White 69"]}
				/>
				<mesh
					geometry={nodes.bomberJacket001_3.geometry}
					material={materials["Carpet fabric"]}
				/>
			</group>
			<group
				position={[-0.01, 0.26, 0.47]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.01}
			>
				<mesh
					geometry={nodes.bomberJacket_1.geometry}
					material={materials.pockets}
				/>
				<mesh
					geometry={nodes.bomberJacket_2.geometry}
					material={nodes.bomberJacket_2.material}
				/>
				<mesh
					geometry={nodes.bomberJacket_3.geometry}
					material={materials["Carpet.002"]}
				/>
				<mesh
					geometry={nodes.bomberJacket_4.geometry}
					material={materials["Carpet - Light Brown 69"]}
				/>
				<mesh
					geometry={nodes.bomberJacket_5.geometry}
					material={materials["PBR fabric carpet"]}
				/>
			</group>
			<mesh
				geometry={nodes.Sphere018.geometry}
				material={materials["Material.015"]}
			/>
			<mesh
				geometry={nodes.Sphere018_1.geometry}
				material={materials["Material.016"]}
			/>
			<mesh
				geometry={nodes.Sphere018_2.geometry}
				material={materials["Material.017"]}
			/>
			<mesh
				geometry={nodes.Sphere018_3.geometry}
				material={nodes.Sphere018_3.material}
			/>
			<mesh
				geometry={nodes.Sphere018_4.geometry}
				material={materials["Material.018"]}
			/>
			<mesh
				geometry={nodes.Sphere018_5.geometry}
				material={materials["Degradable Metal.001"]}
			/>
			<mesh
				geometry={nodes.mesh112.geometry}
				material={nodes.mesh112.material}
			/>
			<mesh
				geometry={nodes.mesh111.geometry}
				material={nodes.mesh111.material}
			/>
			<mesh
				geometry={nodes.mesh110.geometry}
				material={nodes.mesh110.material}
			/>
			<mesh
				geometry={nodes.mesh110_1.geometry}
				material={nodes.mesh110_1.material}
			/>
			<mesh
				geometry={nodes.mesh108.geometry}
				material={nodes.mesh108.material}
			/>
			<mesh
				geometry={nodes.mesh108_1.geometry}
				material={nodes.mesh108_1.material}
			/>
			<mesh
				geometry={nodes.mesh107.geometry}
				material={nodes.mesh107.material}
			/>
			<mesh
				geometry={nodes.mesh107_1.geometry}
				material={nodes.mesh107_1.material}
			/>
			<mesh
				geometry={nodes.mesh097.geometry}
				material={nodes.mesh097.material}
			/>
			<mesh
				geometry={nodes.mesh096.geometry}
				material={nodes.mesh096.material}
			/>
			<mesh
				geometry={nodes.mesh095.geometry}
				material={nodes.mesh095.material}
			/>
			<mesh
				geometry={nodes.mesh088.geometry}
				material={nodes.mesh088.material}
			/>
			<mesh
				geometry={nodes.mesh087.geometry}
				material={nodes.mesh087.material}
			/>
			<mesh
				geometry={nodes.mesh087_1.geometry}
				material={nodes.mesh087_1.material}
			/>
			<mesh
				geometry={nodes.Cylinder076.geometry}
				material={nodes.Cylinder076.material}
			/>
			<mesh
				geometry={nodes.Cylinder076_1.geometry}
				material={nodes.Cylinder076_1.material}
			/>
			<mesh
				geometry={nodes.Cylinder076_2.geometry}
				material={nodes.Cylinder076_2.material}
			/>
			<mesh
				geometry={nodes.Cube013.geometry}
				material={nodes.Cube013.material}
			/>
			<mesh
				geometry={nodes.Cube013_1.geometry}
				material={materials["Wood.001"]}
			/>
			<mesh
				geometry={nodes.Cube013_2.geometry}
				material={materials["Material.024"]}
			/>
			<mesh
				geometry={nodes.Cube013_3.geometry}
				material={materials["Glass.004"]}
			/>
			<mesh
				geometry={nodes.Cube013_4.geometry}
				material={nodes.Cube013_4.material}
			/>
		</group>
	);
}

useGLTF.preload("models/earthyboundNomad_compressed.glb");
