/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/avantGardeBloom.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function AvantGardeBloom(props) {
	const { nodes, materials } = useGLTF("models/avantGardeBloom.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Sphere010.geometry}
				material={materials["Silver fabric procedural"]}
				position={[-0.06, 10.868, -0.416]}
				scale={0.247}
			/>
			<group
				position={[0.116, 10.667, -0.039]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={[0.139, 0.189, 0.135]}
			>
				<mesh
					geometry={nodes.Sphere001.geometry}
					material={materials["Material.001"]}
				/>
				<mesh
					geometry={nodes.Sphere001_1.geometry}
					material={materials["Material.002"]}
				/>
				<mesh
					geometry={nodes.Sphere001_2.geometry}
					material={materials["Material.003"]}
				/>
				<mesh
					geometry={nodes.Sphere001_3.geometry}
					material={materials["Gold.001"]}
				/>
				<mesh
					geometry={nodes.Sphere001_4.geometry}
					material={materials["Material.005"]}
				/>
				<mesh
					geometry={nodes.Sphere001_5.geometry}
					material={materials["Degradable Metal"]}
				/>
			</group>
			<group
				position={[-0.249, 10.667, -0.039]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={[0.139, 0.189, 0.135]}
			>
				<mesh
					geometry={nodes.Sphere001_6.geometry}
					material={materials["Material.001"]}
				/>
				<mesh
					geometry={nodes.Sphere001_7.geometry}
					material={materials["Material.002"]}
				/>
				<mesh
					geometry={nodes.Sphere001_8.geometry}
					material={materials["Material.003"]}
				/>
				<mesh
					geometry={nodes.Sphere001_9.geometry}
					material={materials["Gold.001"]}
				/>
				<mesh
					geometry={nodes.Sphere001_10.geometry}
					material={materials["Material.005"]}
				/>
				<mesh
					geometry={nodes.Sphere001_11.geometry}
					material={materials["Degradable Metal"]}
				/>
			</group>
			<mesh
				geometry={nodes.Retopo_hair.geometry}
				material={materials["Plastic Silver.001"]}
				position={[-0.072, 11.202, -0.187]}
				scale={[0.612, 0.502, 0.502]}
			/>
			<mesh
				geometry={nodes.Retopo_Cube022.geometry}
				material={materials["Plastic Silver.001"]}
				position={[-0.068, 10.638, 0.166]}
				scale={0.247}
			/>
			<mesh
				geometry={nodes.Retopo_Cube021.geometry}
				material={materials.chrome}
				position={[-0.061, 10.648, -0.187]}
				scale={0.247}
			/>
			<mesh
				geometry={nodes.Retopo_Cube020.geometry}
				material={materials.chrome}
				position={[-0.06, 11.139, -0.278]}
				scale={0.247}
			/>
			<group position={[-0.065, 10.638, 0.189]} scale={0.247}>
				<mesh
					geometry={nodes.mesh019.geometry}
					material={materials["Chrome.001"]}
				/>
				<mesh
					geometry={nodes.mesh019_1.geometry}
					material={materials["Plastic Silver.001"]}
				/>
			</group>
			<mesh
				geometry={nodes.Retopo_Cube018.geometry}
				material={materials["Chrome.001"]}
				position={[-0.065, 10.639, 0.202]}
				scale={0.247}
			/>
			<mesh
				geometry={nodes.Retopo_Cube017.geometry}
				material={materials.chrome}
				position={[-0.065, 10.629, 0.21]}
				scale={0.247}
			/>
			<mesh
				geometry={nodes.Retopo_Cube016.geometry}
				material={materials["Gold Shiny Clean.001"]}
				position={[-0.072, 10.654, -0.364]}
				rotation={[0.513, 0, 0]}
				scale={0.247}
			/>
			<mesh
				geometry={nodes.Retopo_Cube015.geometry}
				material={materials.chrome}
				position={[-0.061, 10.632, -0.187]}
				scale={0.247}
			/>
			<mesh
				geometry={nodes.Retopo_Cube014.geometry}
				material={materials["Material.009"]}
				position={[-0.061, 10.648, -0.187]}
				scale={0.247}
			/>
			<group
				position={[-0.059, 10.775, -0.884]}
				rotation={[1.468, 0, Math.PI]}
				scale={0.112}
			>
				<mesh
					geometry={nodes.Plane003.geometry}
					material={materials["Gold Shiny Clean.001"]}
				/>
				<mesh
					geometry={nodes.Plane003_1.geometry}
					material={materials["Material.011"]}
				/>
			</group>
			<mesh
				geometry={nodes.NurbsPath034.geometry}
				material={materials["Material.012"]}
				position={[-0.064, 10.79, -1.337]}
				rotation={[0, Math.PI / 2, 0]}
				scale={0.247}
			/>
			<mesh
				geometry={nodes.leg_r.geometry}
				material={materials["Plastic Silver"]}
				position={[-0.68, 2.68, -0.269]}
				rotation={[Math.PI, 0, 0.021]}
				scale={-0.24}
			/>
			<mesh
				geometry={nodes.leg_l.geometry}
				material={materials["Plastic Silver"]}
				position={[0.595, 2.68, -0.269]}
				rotation={[0, 0, 0.021]}
				scale={0.24}
			/>
			<mesh
				geometry={nodes.largePuffer003.geometry}
				material={materials["Yellow wool"]}
				position={[-0.038, 0.31, 0.53]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.007}
			/>
			<mesh
				geometry={nodes.largePuffer.geometry}
				material={materials["Sequints Pattern Fabric"]}
				position={[-0.078, 4.433, 0.62]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.007}
			/>
			<group position={[-19.005, 0, 0]}>
				<mesh
					geometry={nodes["Geo-Scatter_Merged_Export_1"].geometry}
					material={materials["White Flower.001"]}
				/>
				<mesh
					geometry={nodes["Geo-Scatter_Merged_Export_2"].geometry}
					material={materials["M_Flower_Sunflower.001"]}
				/>
				<mesh
					geometry={nodes["Geo-Scatter_Merged_Export_3"].geometry}
					material={materials["Flower Vase_Assorted Color.003"]}
				/>
			</group>
			<group
				position={[-0.066, 10.691, -0.189]}
				rotation={[0, 0, -Math.PI / 2]}
				scale={0.247}
			>
				<mesh
					geometry={nodes.Cylinder039_1.geometry}
					material={materials["Chrome.001"]}
				/>
				<mesh
					geometry={nodes.Cylinder039_2.geometry}
					material={materials["Material.014"]}
				/>
			</group>
			<group
				position={[-0.06, 11.106, -0.757]}
				rotation={[2.199, 0, 0]}
				scale={-0.193}
			>
				<mesh
					geometry={nodes.Cylinder038_1.geometry}
					material={materials["Plastic Silver.001"]}
				/>
				<mesh
					geometry={nodes.Cylinder038_2.geometry}
					material={materials["Material.013"]}
				/>
				<mesh
					geometry={nodes.Cylinder038_3.geometry}
					material={materials["Chrome.001"]}
				/>
			</group>
			<group
				position={[0.303, 10.951, -0.583]}
				rotation={[-0.022, 0.439, -1.432]}
				scale={0.193}
			>
				<mesh
					geometry={nodes.Cylinder037_1.geometry}
					material={materials["Plastic Silver.001"]}
				/>
				<mesh
					geometry={nodes.Cylinder037_2.geometry}
					material={materials["Material.013"]}
				/>
				<mesh
					geometry={nodes.Cylinder037_3.geometry}
					material={materials["Chrome.001"]}
				/>
			</group>
			<group
				position={[0.216, 10.794, -0.717]}
				rotation={[-0.058, 0.774, -1.675]}
				scale={0.193}
			>
				<mesh
					geometry={nodes.Cylinder036_1.geometry}
					material={materials["Plastic Silver.001"]}
				/>
				<mesh
					geometry={nodes.Cylinder036_2.geometry}
					material={materials["Material.013"]}
				/>
				<mesh
					geometry={nodes.Cylinder036_3.geometry}
					material={materials["Chrome.001"]}
				/>
			</group>
			<group
				position={[0.097, 10.955, -0.796]}
				rotation={[0.718, 1.258, -1.985]}
				scale={0.193}
			>
				<mesh
					geometry={nodes.Cylinder035_1.geometry}
					material={materials["Plastic Silver.001"]}
				/>
				<mesh
					geometry={nodes.Cylinder035_2.geometry}
					material={materials["Material.013"]}
				/>
				<mesh
					geometry={nodes.Cylinder035_3.geometry}
					material={materials["Chrome.001"]}
				/>
			</group>
			<group
				position={[0.183, 11.105, -0.663]}
				rotation={[0.097, 0.814, -1.097]}
				scale={0.175}
			>
				<mesh
					geometry={nodes.Cylinder034_1.geometry}
					material={materials["Plastic Silver.001"]}
				/>
				<mesh
					geometry={nodes.Cylinder034_2.geometry}
					material={materials["Material.013"]}
				/>
				<mesh
					geometry={nodes.Cylinder034_3.geometry}
					material={materials["Chrome.001"]}
				/>
			</group>
			<group
				position={[0.038, 11.23, -0.618]}
				rotation={[0.115, 1.245, -0.731]}
				scale={0.132}
			>
				<mesh
					geometry={nodes.Cylinder033_1.geometry}
					material={materials["Plastic Silver.001"]}
				/>
				<mesh
					geometry={nodes.Cylinder033_2.geometry}
					material={materials["Material.013"]}
				/>
				<mesh
					geometry={nodes.Cylinder033_3.geometry}
					material={materials["Chrome.001"]}
				/>
			</group>
			<group
				position={[0.162, 11.239, -0.505]}
				rotation={[0.289, 0.683, -0.81]}
				scale={0.104}
			>
				<mesh
					geometry={nodes.Cylinder032_1.geometry}
					material={materials["Plastic Silver.001"]}
				/>
				<mesh
					geometry={nodes.Cylinder032_2.geometry}
					material={materials["Material.013"]}
				/>
				<mesh
					geometry={nodes.Cylinder032_3.geometry}
					material={materials["Chrome.001"]}
				/>
			</group>
			<group
				position={[-0.425, 10.951, -0.583]}
				rotation={[3.12, 0.439, -1.432]}
				scale={-0.193}
			>
				<mesh
					geometry={nodes.Cylinder026_1.geometry}
					material={materials["Plastic Silver.001"]}
				/>
				<mesh
					geometry={nodes.Cylinder026_2.geometry}
					material={materials["Material.013"]}
				/>
				<mesh
					geometry={nodes.Cylinder026_3.geometry}
					material={materials["Chrome.001"]}
				/>
			</group>
			<group
				position={[-0.338, 10.794, -0.717]}
				rotation={[3.083, 0.774, -1.675]}
				scale={-0.193}
			>
				<mesh
					geometry={nodes.Cylinder006.geometry}
					material={materials["Plastic Silver.001"]}
				/>
				<mesh
					geometry={nodes.Cylinder006_1.geometry}
					material={materials["Material.013"]}
				/>
				<mesh
					geometry={nodes.Cylinder006_2.geometry}
					material={materials["Chrome.001"]}
				/>
			</group>
			<group
				position={[-0.219, 10.955, -0.796]}
				rotation={[-2.424, 1.258, -1.985]}
				scale={-0.193}
			>
				<mesh
					geometry={nodes.Cylinder011.geometry}
					material={materials["Plastic Silver.001"]}
				/>
				<mesh
					geometry={nodes.Cylinder011_1.geometry}
					material={materials["Material.013"]}
				/>
				<mesh
					geometry={nodes.Cylinder011_2.geometry}
					material={materials["Chrome.001"]}
				/>
			</group>
			<group
				position={[-0.305, 11.105, -0.663]}
				rotation={[-3.045, 0.814, -1.097]}
				scale={-0.175}
			>
				<mesh
					geometry={nodes.Cylinder012.geometry}
					material={materials["Plastic Silver.001"]}
				/>
				<mesh
					geometry={nodes.Cylinder012_1.geometry}
					material={materials["Material.013"]}
				/>
				<mesh
					geometry={nodes.Cylinder012_2.geometry}
					material={materials["Chrome.001"]}
				/>
			</group>
			<group
				position={[-0.161, 11.23, -0.618]}
				rotation={[-3.026, 1.245, -0.731]}
				scale={-0.132}
			>
				<mesh
					geometry={nodes.Cylinder005.geometry}
					material={materials["Plastic Silver.001"]}
				/>
				<mesh
					geometry={nodes.Cylinder005_1.geometry}
					material={materials["Material.013"]}
				/>
				<mesh
					geometry={nodes.Cylinder005_2.geometry}
					material={materials["Chrome.001"]}
				/>
			</group>
			<group
				position={[-0.285, 11.239, -0.505]}
				rotation={[-2.852, 0.683, -0.81]}
				scale={-0.104}
			>
				<mesh
					geometry={nodes.Cylinder004.geometry}
					material={materials["Plastic Silver.001"]}
				/>
				<mesh
					geometry={nodes.Cylinder004_1.geometry}
					material={materials["Material.013"]}
				/>
				<mesh
					geometry={nodes.Cylinder004_2.geometry}
					material={materials["Chrome.001"]}
				/>
			</group>
			<group
				position={[-0.063, 10.789, -2.864]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={[0.066, 0.05, 0.066]}
			>
				<mesh
					geometry={nodes.Cylinder003.geometry}
					material={materials["Plastic Silver.001"]}
				/>
				<mesh
					geometry={nodes.Cylinder003_1.geometry}
					material={materials["Pyrex Glass"]}
				/>
				<mesh
					geometry={nodes.Cylinder003_2.geometry}
					material={materials["Chrome.001"]}
				/>
			</group>
			<mesh
				geometry={nodes.Retopo_body002_AnkleGlass001.geometry}
				material={materials.AnkleGlass}
				position={[-0.045, 0.144, -0.259]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.253}
			/>
			<mesh
				geometry={nodes.Retopo_body002_bodyBase001.geometry}
				material={materials.bodyBase}
				position={[-0.045, 0.144, -0.259]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.253}
			/>
			<mesh
				geometry={nodes.Retopo_body002_bodyCeramic001.geometry}
				material={materials.bodyCeramic}
				position={[-0.045, 0.144, -0.259]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.253}
			/>
			<mesh
				geometry={nodes.Retopo_body002_fingerLight001.geometry}
				material={materials.fingerLight}
				position={[-0.045, 0.144, -0.259]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.253}
			/>
			<mesh
				geometry={nodes.Retopo_body002_glass_joints001.geometry}
				material={materials.glass_joints}
				position={[-0.045, 0.144, -0.259]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.253}
			/>
			<mesh
				geometry={nodes.Retopo_body002_gold_Body001.geometry}
				material={materials.gold_Body}
				position={[-0.045, 0.144, -0.259]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.253}
			/>
			<mesh
				geometry={nodes.Retopo_body002_Iridescent_Ceramic001.geometry}
				material={materials["Carbon Fiber"]}
				position={[-0.045, 0.144, -0.259]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.253}
			/>
			<mesh
				geometry={nodes.Retopo_body002_shoeBottom001.geometry}
				material={materials.shoeBottom}
				position={[-0.045, 0.144, -0.259]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.253}
			/>
			<mesh
				geometry={nodes.Retopo_body002_shoeLight001.geometry}
				material={materials.shoeLight}
				position={[-0.045, 0.144, -0.259]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.253}
			/>
			<mesh
				geometry={nodes.Retopo_body002_shoeSilver001.geometry}
				material={materials.shoeSilver}
				position={[-0.045, 0.144, -0.259]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.253}
			/>
			<mesh
				geometry={nodes.Retopo_body002_shoeSole_wood001.geometry}
				material={materials["Soft Neon Lamp"]}
				position={[-0.045, 0.144, -0.259]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.253}
			/>
			<mesh
				geometry={nodes.Retopo_body002_thighGlass001.geometry}
				material={materials.thighGlass}
				position={[-0.045, 0.144, -0.259]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.253}
			/>
		</group>
	);
}

useGLTF.preload("models/avantGardeBloom.glb");
