/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function EnvironmentMap(props) {
	const { nodes, materials } = useGLTF("models/envrionmentBlockOut.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube.geometry}
				material={materials.Material}
				position={[-0.281, 8.101, 0]}
				scale={[1.149, 1, 1]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube001.geometry}
				material={materials.Material}
				position={[-0.281, 8.101, 0]}
				scale={[1.149, 1, 1]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder.geometry}
				material={materials.Material}
				position={[0, 1.372, -11.413]}
				scale={[6.429, 0.728, 6.429]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane.geometry}
				material={materials.Material}
				position={[-0.079, 8.349, -21.829]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle042.geometry}
				material={materials.Material}
				position={[-34.477, 5.306, -8.112]}
				rotation={[0, 0, -Math.PI / 2]}
				scale={3.06}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle041.geometry}
				material={materials.Material}
				position={[-34.477, 5.306, -8.112]}
				rotation={[0, 0, -Math.PI / 2]}
				scale={3.06}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle040.geometry}
				material={materials.Material}
				position={[-34.458, 5.358, -8.112]}
				rotation={[0, 0, -Math.PI / 2]}
				scale={3.07}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle033.geometry}
				material={materials.Material}
				position={[-21.349, 5.306, -8.112]}
				rotation={[-Math.PI, 0, -Math.PI / 2]}
				scale={-3.06}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle032.geometry}
				material={materials.Material}
				position={[-21.349, 5.306, -8.112]}
				rotation={[-Math.PI, 0, -Math.PI / 2]}
				scale={-3.06}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle001.geometry}
				material={materials.Material}
				position={[20.552, 5.306, -8.112]}
				rotation={[0, 0, -Math.PI / 2]}
				scale={3.06}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle002.geometry}
				material={materials.Material}
				position={[20.552, 5.306, -8.112]}
				rotation={[0, 0, -Math.PI / 2]}
				scale={3.06}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle003.geometry}
				material={materials.Material}
				position={[20.571, 5.358, -8.112]}
				rotation={[0, 0, -Math.PI / 2]}
				scale={3.07}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle004.geometry}
				material={materials.Material}
				position={[33.679, 5.306, -8.112]}
				rotation={[-Math.PI, 0, -Math.PI / 2]}
				scale={-3.06}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle005.geometry}
				material={materials.Material}
				position={[33.679, 5.306, -8.112]}
				rotation={[-Math.PI, 0, -Math.PI / 2]}
				scale={-3.06}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube002.geometry}
				material={materials.Material}
				position={[-0.264, 2.639, 7.367]}
				scale={[4.041, 2.771, 3.754]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube003.geometry}
				material={materials.Material}
				position={[-0.264, 13.493, 7.367]}
				scale={[4.041, 2.59, 3.754]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube004.geometry}
				material={materials.Material}
				position={[0, 22.105, -11.399]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane001.geometry}
				material={materials.Material}
				position={[-0.079, 8.349, -21.829]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={[0.974, 1, 1]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube005.geometry}
				material={materials.Material}
				position={[-29.537, 21.495, -8.266]}
				scale={6.373}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube006.geometry}
				material={materials.Material}
				position={[28.996, 21.495, -8.266]}
				scale={[6.649, 6.373, 6.373]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane003.geometry}
				material={materials.Material}
				position={[-17.375, 8.349, -52.961]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube007.geometry}
				material={materials.Material}
				position={[72.707, 21.495, -8.266]}
				scale={[6.649, 6.373, 6.373]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane004.geometry}
				material={materials.Material}
				position={[-17.403, 8.349, -52.961]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane005.geometry}
				material={materials.Material}
				position={[-16.009, 8.349, -20.18]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane006.geometry}
				material={materials.Material}
				position={[-37.63, 8.349, -20.119]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane007.geometry}
				material={materials.Material}
				position={[-16.009, 8.349, -54.689]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane008.geometry}
				material={materials.Material}
				position={[-37.63, 8.349, -54.628]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane010.geometry}
				material={materials.Material}
				position={[133.222, 8.349, -20.18]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane011.geometry}
				material={materials.Material}
				position={[111.6, 8.349, -20.119]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane012.geometry}
				material={materials.Material}
				position={[133.222, 8.349, -54.689]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane013.geometry}
				material={materials.Material}
				position={[111.6, 8.349, -54.628]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle006.geometry}
				material={materials.Material}
				position={[-47.498, 5.306, -8.112]}
				rotation={[0, 0, -Math.PI / 2]}
				scale={3.06}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle007.geometry}
				material={materials.Material}
				position={[-47.498, 5.306, -8.112]}
				rotation={[0, 0, -Math.PI / 2]}
				scale={3.06}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle008.geometry}
				material={materials.Material}
				position={[-47.479, 5.358, -8.112]}
				rotation={[0, 0, -Math.PI / 2]}
				scale={3.07}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle009.geometry}
				material={materials.Material}
				position={[-34.371, 5.306, -8.112]}
				rotation={[-Math.PI, 0, -Math.PI / 2]}
				scale={-3.06}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle010.geometry}
				material={materials.Material}
				position={[-34.371, 5.306, -8.112]}
				rotation={[-Math.PI, 0, -Math.PI / 2]}
				scale={-3.06}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle011.geometry}
				material={materials.Material}
				position={[45.355, 5.306, -8.112]}
				rotation={[0, 0, -Math.PI / 2]}
				scale={3.06}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle012.geometry}
				material={materials.Material}
				position={[45.355, 5.306, -8.112]}
				rotation={[0, 0, -Math.PI / 2]}
				scale={3.06}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle013.geometry}
				material={materials.Material}
				position={[45.374, 5.358, -8.112]}
				rotation={[0, 0, -Math.PI / 2]}
				scale={3.07}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle014.geometry}
				material={materials.Material}
				position={[58.482, 5.306, -8.112]}
				rotation={[-Math.PI, 0, -Math.PI / 2]}
				scale={-3.06}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle015.geometry}
				material={materials.Material}
				position={[58.482, 5.306, -8.112]}
				rotation={[-Math.PI, 0, -Math.PI / 2]}
				scale={-3.06}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle016.geometry}
				material={materials.Material}
				position={[33.945, 5.306, -8.112]}
				rotation={[0, 0, -Math.PI / 2]}
				scale={[3.06, 2.591, 3.06]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle017.geometry}
				material={materials.Material}
				position={[33.945, 5.306, -8.112]}
				rotation={[0, 0, -Math.PI / 2]}
				scale={[3.06, 2.591, 3.06]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle018.geometry}
				material={materials.Material}
				position={[33.961, 5.358, -8.112]}
				rotation={[0, 0, -Math.PI / 2]}
				scale={[3.07, 2.599, 3.07]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle019.geometry}
				material={materials.Material}
				position={[45.059, 5.306, -8.112]}
				rotation={[-Math.PI, 0, -Math.PI / 2]}
				scale={[-3.06, -2.591, -3.06]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle020.geometry}
				material={materials.Material}
				position={[45.059, 5.306, -8.112]}
				rotation={[-Math.PI, 0, -Math.PI / 2]}
				scale={[-3.06, -2.591, -3.06]}
			/>
		</group>
	);
}

useGLTF.preload("models/envrionmentBlockOut.glb");
