/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef, useEffect } from "react";
import { useGLTF, PerspectiveCamera, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

export function EnvironmentWithCamera({
	playAnimation,
	paused,
	breakpoints = [],
	currentBreakpointIndex,
	onBreakpointHit,
	...props
}) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF(
		"models/capstoneEnvironement-camera.glb"
	);
	const { actions } = useAnimations(animations, group);

	/**
	 * 1) Once materials load, tweak roughness, metalness, and texture encodings
	 *    to make them look nicer.
	 */
	useEffect(() => {
		if (!materials) return;

		Object.values(materials).forEach((material) => {
			if (material instanceof THREE.MeshStandardMaterial) {
				// Adjust material properties
				material.roughness = 0.2;
				material.metalness = 1;

				// Ensure color textures use sRGBEncoding
				if (material.map) {
					material.map.encoding = THREE.sRGBEncoding;
					material.map.anisotropy = 36;
				}
				// If using normal maps, increase anisotropy as well
				if (material.normalMap) {
					material.normalMap.anisotropy = 36;
				}
				// You can repeat for roughnessMap, displacementMap, etc. if needed
			}
		});
	}, [materials]);

	/**
	 * 2) Start/stop animations when `playAnimation` changes
	 */
	useEffect(() => {
		if (!actions) return;

		if (playAnimation) {
			// For each animation action, reset, set to LoopOnce, clamp, and play
			Object.values(actions).forEach((action) => {
				action.setLoop(THREE.LoopOnce, 1);
				action.clampWhenFinished = true;
				action.reset().play();
				action.paused = false;
			});
		} else {
			// Stop all actions
			Object.values(actions).forEach((action) => action.stop());
		}
	}, [playAnimation, actions]);

	/**
	 * 3) Pause/unpause animations when `paused` changes
	 */
	useEffect(() => {
		if (!actions) return;

		// Only apply if actually playing
		if (playAnimation) {
			Object.values(actions).forEach((action) => {
				action.paused = paused;
			});
		}
	}, [paused, playAnimation, actions]);

	/**
	 * 4) On every frame, check if we crossed a breakpoint & log the current frame
	 */
	useFrame(() => {
		if (!playAnimation || !actions || paused) return;

		const [firstAction] = Object.values(actions);
		if (!firstAction) return;

		const fps = 24; // Adjust if your animation uses a different fps
		const currentFrame = Math.floor(firstAction.time * fps);

		// Optional: log the current frame
		console.log(`Frame: ${currentFrame}`);

		// Check if we hit a breakpoint
		if (currentBreakpointIndex < breakpoints.length) {
			const targetFrame = breakpoints[currentBreakpointIndex];
			if (currentFrame >= targetFrame) {
				console.log(`Hit breakpoint at frame ${targetFrame}`);
				onBreakpointHit?.(currentBreakpointIndex);
			}
		}
	});
	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Scene">
				<PerspectiveCamera
					name="Camera"
					makeDefault={true}
					far={1000}
					near={0.1}
					fov={28.409}
					position={[-90.066, 6.599, 7.5]}
					rotation={[0, -Math.PI / 2, 0]}
					receiveShadow={true}
				/>
				<directionalLight
					name="Light"
					intensity={2}
					decay={0}
					position={[5.019, 183.52, 3.295]}
					rotation={[-1.154, 0.324, 0.496]}
				>
					<group position={[0, 0, -1]} />
				</directionalLight>
				<mesh
					name="Circle001"
					castShadow
					receiveShadow={true}
					geometry={nodes.Circle001.geometry}
					material={materials["Material.114"]}
					position={[20.552, 5.306, -9.455]}
					rotation={[0, 0, -Math.PI / 2]}
					scale={3.06}
				/>
				<mesh
					name="Circle002"
					castShadow
					receiveShadow
					geometry={nodes.Circle002.geometry}
					material={materials["Marble.011"]}
					position={[20.552, 5.306, -9.455]}
					rotation={[0, 0, -Math.PI / 2]}
					scale={3.06}
				/>
				<mesh
					name="Circle032"
					castShadow
					receiveShadow
					geometry={nodes.Circle032.geometry}
					material={materials["Marble.012"]}
					position={[-27.81, 5.306, -9.455]}
					rotation={[-Math.PI, 0, -Math.PI / 2]}
					scale={-3.06}
				/>
				<mesh
					name="Cube001"
					castShadow
					receiveShadow
					geometry={nodes.Cube001.geometry}
					material={materials["Material.115"]}
					position={[-40.154, 7.823, 30.196]}
					scale={[1, 0.852, 1]}
				/>
				<mesh
					name="Cube002"
					castShadow
					receiveShadow
					geometry={nodes.Cube002.geometry}
					material={materials["Material.116"]}
					position={[-46.896, 1.841, 32.028]}
					rotation={[Math.PI, 0, Math.PI]}
					scale={[5.549, 1.987, 2.131]}
				/>
				<mesh
					name="Cube003_1"
					castShadow
					receiveShadow
					geometry={nodes.Cube003_1.geometry}
					material={materials["SciFi Structural Panelling.015"]}
					position={[-70.656, 21.742, -66.465]}
				/>
				<mesh
					name="Cube003_2"
					castShadow
					receiveShadow
					geometry={nodes.Cube003_2.geometry}
					material={materials["Glass.006"]}
					position={[-70.656, 21.742, -66.465]}
				/>
				<mesh
					name="Cube003_3"
					castShadow
					receiveShadow
					geometry={nodes.Cube003_3.geometry}
					material={materials["Material.118"]}
					position={[-70.656, 21.742, -66.465]}
				/>
				<mesh
					name="Cube003_4"
					castShadow
					receiveShadow
					geometry={nodes.Cube003_4.geometry}
					material={materials["Scifi Fabric Panels 01.016"]}
					position={[-70.656, 21.742, -66.465]}
				/>
				<mesh
					name="Cube004_1"
					castShadow
					receiveShadow
					geometry={nodes.Cube004_1.geometry}
					material={materials["Material.119"]}
					position={[-70.656, 21.742, -66.465]}
				/>
				<mesh
					name="Cube004_2"
					castShadow
					receiveShadow
					geometry={nodes.Cube004_2.geometry}
					material={materials["Material.120"]}
					position={[-70.656, 21.742, -66.465]}
				/>
				<mesh
					name="Cube005_1"
					castShadow
					receiveShadow
					geometry={nodes.Cube005_1.geometry}
					material={materials["Material.121"]}
					position={[-70.656, 21.742, -66.465]}
				/>
				<mesh
					name="Cube005_2"
					castShadow
					receiveShadow
					geometry={nodes.Cube005_2.geometry}
					material={materials["Azul Macaubas Blue Marble.003"]}
					position={[-70.656, 21.742, -66.465]}
				/>
				<mesh
					name="Cube010_4"
					castShadow
					receiveShadow
					geometry={nodes.Cube010_4.geometry}
					material={materials["Scifi Fabric Panels 01.017"]}
					position={[-23.398, 21.742, -69.287]}
				/>
				<mesh
					name="Cube015"
					castShadow
					receiveShadow
					geometry={nodes.Cube015.geometry}
					material={materials["Material.117"]}
					position={[77.744, 5.363, 7.002]}
				/>
				<mesh
					name="Cube016"
					castShadow
					receiveShadow
					geometry={nodes.Cube016.geometry}
					material={materials["Marble.013"]}
					position={[0.072, 0.795, -20.698]}
				/>
				<mesh
					name="Cube020"
					castShadow
					receiveShadow
					geometry={nodes.Cube020.geometry}
					material={materials["Material.122"]}
					position={[-70.656, 21.742, -66.465]}
				/>
				<mesh
					name="Cube021"
					castShadow
					receiveShadow
					geometry={nodes.Cube021.geometry}
					material={materials["Material.123"]}
					position={[169.134, 63.918, 7.106]}
				/>
				<mesh
					name="Cube022_1"
					castShadow
					receiveShadow
					geometry={nodes.Cube022_1.geometry}
					material={materials["Black Marble.004"]}
					position={[169.134, 63.918, 7.106]}
				/>
				<mesh
					name="Cube022_2"
					castShadow
					receiveShadow
					geometry={nodes.Cube022_2.geometry}
					material={materials["Glass.005"]}
					position={[169.134, 63.918, 7.106]}
				/>
				<mesh
					name="Cube024_2"
					castShadow
					receiveShadow
					geometry={nodes.Cube024_2.geometry}
					material={materials["Colorful Marble.003"]}
					position={[-23.398, 21.742, -69.287]}
				/>
				<mesh
					name="Cube027_4"
					castShadow
					receiveShadow
					geometry={nodes.Cube027_4.geometry}
					material={materials["Scifi Fabric Panels 01.018"]}
					position={[24.124, 21.742, -69.287]}
				/>
				<mesh
					name="Cube029_2"
					castShadow
					receiveShadow
					geometry={nodes.Cube029_2.geometry}
					material={materials["Marble.014"]}
					position={[24.124, 21.742, -69.287]}
				/>
				<mesh
					name="Cube032_4"
					castShadow
					receiveShadow
					geometry={nodes.Cube032_4.geometry}
					material={materials["Scifi Fabric Panels 01.019"]}
					position={[71.52, 21.742, -69.287]}
				/>
				<mesh
					name="Cube034_2"
					castShadow
					receiveShadow
					geometry={nodes.Cube034_2.geometry}
					material={materials["Brown Marble.003"]}
					position={[71.52, 21.742, -69.287]}
				/>
				<mesh
					name="Cube039"
					castShadow
					receiveShadow
					geometry={nodes.Cube039.geometry}
					material={materials["Material.124"]}
					position={[77.742, 8.78, 7.078]}
				/>
				<mesh
					name="Cube039_1"
					castShadow
					receiveShadow
					geometry={nodes.Cube039_1.geometry}
					material={materials["Material.125"]}
					position={[77.742, 8.78, 7.078]}
				/>
				<mesh
					name="Cube082"
					castShadow
					receiveShadow
					geometry={nodes.Cube082.geometry}
					material={materials["Fabric.004"]}
					position={[98.351, 36.741, 6.785]}
				/>
				<mesh
					name="Cube084"
					castShadow
					receiveShadow
					geometry={nodes.Cube084.geometry}
					material={materials["PBR fresh gold.005"]}
					position={[220.633, 37.539, 7.764]}
				/>
				<mesh
					name="Cube084_1"
					castShadow
					receiveShadow
					geometry={nodes.Cube084_1.geometry}
					material={materials["Material.126"]}
					position={[220.633, 37.539, 7.764]}
				/>
				<mesh
					name="Cube085"
					castShadow
					receiveShadow
					geometry={nodes.Cube085.geometry}
					material={materials["Material.127"]}
					position={[151.517, 36.362, -7.343]}
					scale={[30.885, 1, 0.175]}
				/>
				<mesh
					name="Cube103"
					castShadow
					receiveShadow
					geometry={nodes.Cube103.geometry}
					material={materials["Material.128"]}
					position={[162.445, 51.281, -52.199]}
				/>
				<mesh
					name="Cylinder001"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder001.geometry}
					material={materials["SciFi Structural Panelling.016"]}
					position={[-72.451, 12.279, 7.092]}
					rotation={[1.178, 0, -Math.PI / 2]}
					scale={[2.226, 2.192, 2.226]}
				/>
				<mesh
					name="Cylinder046"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder046.geometry}
					material={materials["SciFi Structural Panelling.017"]}
					position={[-72.451, 10.118, 7.092]}
					rotation={[1.178, 0, -Math.PI / 2]}
					scale={[2.226, 2.192, 2.226]}
				/>
				<mesh
					name="Cylinder046_1"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder046_1.geometry}
					material={materials["Material.129"]}
					position={[-72.451, 10.118, 7.092]}
					rotation={[1.178, 0, -Math.PI / 2]}
					scale={[2.226, 2.192, 2.226]}
				/>
				<mesh
					name="Cylinder046_2"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder046_2.geometry}
					material={materials["Concrete.003"]}
					position={[-72.451, 10.118, 7.092]}
					rotation={[1.178, 0, -Math.PI / 2]}
					scale={[2.226, 2.192, 2.226]}
				/>
				<mesh
					name="furniture007"
					castShadow
					receiveShadow
					geometry={nodes.furniture007.geometry}
					material={materials["Material.130"]}
					position={[208.242, 39.293, 17.059]}
					rotation={[Math.PI / 2, 0, Math.PI]}
					scale={0.496}
				/>
				<mesh
					name="furniture007_2"
					castShadow
					receiveShadow
					geometry={nodes.furniture007_2.geometry}
					material={materials["Material.131"]}
					position={[208.242, 39.293, 17.059]}
					rotation={[Math.PI / 2, 0, Math.PI]}
					scale={0.496}
				/>
				<mesh
					name="image_(4)_-_Copy001_1"
					castShadow
					receiveShadow
					geometry={nodes["image_(4)_-_Copy001_1"].geometry}
					material={materials["image (4) - Copy.010"]}
					position={[235.064, 52.792, 7.889]}
					rotation={[Math.PI / 2, 0, -Math.PI / 2]}
					scale={6.263}
				/>
				<mesh
					name="image_(4)_-_Copy002_1"
					castShadow
					receiveShadow
					geometry={nodes["image_(4)_-_Copy002_1"].geometry}
					material={materials["image (4) - Copy.011"]}
					position={[235.064, 52.792, -1.509]}
					rotation={[Math.PI / 2, 0, -Math.PI / 2]}
					scale={6.263}
				/>
				<mesh
					name="image_(4)_-_Copy_1"
					castShadow
					receiveShadow
					geometry={nodes["image_(4)_-_Copy_1"].geometry}
					material={materials["image (4) - Copy.009"]}
					position={[235.064, 52.792, 17.137]}
					rotation={[Math.PI / 2, 0, -Math.PI / 2]}
					scale={6.263}
				/>
				<mesh
					name="image_(4)_-_Copy_2"
					castShadow
					receiveShadow
					geometry={nodes["image_(4)_-_Copy_2"].geometry}
					material={materials["PBR old scratched silver.003"]}
					position={[235.064, 52.792, 17.137]}
					rotation={[Math.PI / 2, 0, -Math.PI / 2]}
					scale={6.263}
				/>
				<mesh
					name="image_(4)_-_Copy_3"
					castShadow
					receiveShadow
					geometry={nodes["image_(4)_-_Copy_3"].geometry}
					material={materials["Material.132"]}
					position={[235.064, 52.792, 17.137]}
					rotation={[Math.PI / 2, 0, -Math.PI / 2]}
					scale={6.263}
				/>
				<group name="Node_60">
					<mesh
						name="Mesh_3"
						castShadow
						receiveShadow
						geometry={nodes.Mesh_3.geometry}
						material={materials["Sci Fi Wall Metallic.003"]}
						position={[-39.975, -0.358, 42.952]}
						rotation={[Math.PI, 0, Math.PI]}
						scale={[0.5, 1.648, 1.768]}
					/>
					<mesh
						name="Mesh_3001"
						castShadow
						receiveShadow
						geometry={nodes.Mesh_3001.geometry}
						material={materials["Sci Fi Wall Metallic.003"]}
						position={[60.681, -0.358, 42.952]}
						rotation={[Math.PI, 0, Math.PI]}
						scale={[0.5, 1.648, 1.768]}
					/>
					<mesh
						name="Mesh_3002"
						castShadow
						receiveShadow
						geometry={nodes.Mesh_3002.geometry}
						material={materials["Sci Fi Wall Metallic.003"]}
						position={[-53.349, -0.358, 42.952]}
						rotation={[Math.PI, 0, Math.PI]}
						scale={[0.6, 1.648, 1.768]}
					/>
					<mesh
						name="Mesh_3003"
						castShadow
						receiveShadow
						geometry={nodes.Mesh_3003.geometry}
						material={materials["Sci Fi Wall Metallic.003"]}
						position={[-28.829, -0.358, 42.952]}
						rotation={[Math.PI, 0, Math.PI]}
						scale={[0.5, 1.648, 1.768]}
					/>
					<mesh
						name="Mesh_3004"
						castShadow
						receiveShadow
						geometry={nodes.Mesh_3004.geometry}
						material={materials["Sci Fi Wall Metallic.003"]}
						position={[-17.652, -0.358, 42.952]}
						rotation={[Math.PI, 0, Math.PI]}
						scale={[0.5, 1.648, 1.768]}
					/>
					<mesh
						name="Mesh_3005"
						castShadow
						receiveShadow
						geometry={nodes.Mesh_3005.geometry}
						material={materials["Sci Fi Wall Metallic.003"]}
						position={[-6.431, -0.358, 42.952]}
						rotation={[Math.PI, 0, Math.PI]}
						scale={[0.5, 1.648, 1.768]}
					/>
					<mesh
						name="Mesh_3006"
						castShadow
						receiveShadow
						geometry={nodes.Mesh_3006.geometry}
						material={materials["Sci Fi Wall Metallic.003"]}
						position={[4.734, -0.358, 42.952]}
						rotation={[Math.PI, 0, Math.PI]}
						scale={[0.5, 1.648, 1.768]}
					/>
					<mesh
						name="Mesh_3007"
						castShadow
						receiveShadow
						geometry={nodes.Mesh_3007.geometry}
						material={materials["Sci Fi Wall Metallic.003"]}
						position={[15.955, -0.358, 42.952]}
						rotation={[Math.PI, 0, Math.PI]}
						scale={[0.5, 1.648, 1.768]}
					/>
					<mesh
						name="Mesh_3008"
						castShadow
						receiveShadow
						geometry={nodes.Mesh_3008.geometry}
						material={materials["Sci Fi Wall Metallic.003"]}
						position={[27.177, -0.358, 42.952]}
						rotation={[Math.PI, 0, Math.PI]}
						scale={[0.5, 1.648, 1.768]}
					/>
					<mesh
						name="Mesh_3009"
						castShadow
						receiveShadow
						geometry={nodes.Mesh_3009.geometry}
						material={materials["Sci Fi Wall Metallic.003"]}
						position={[38.318, -0.358, 42.952]}
						rotation={[Math.PI, 0, Math.PI]}
						scale={[0.5, 1.648, 1.768]}
					/>
					<mesh
						name="Mesh_3010"
						castShadow
						receiveShadow
						geometry={nodes.Mesh_3010.geometry}
						material={materials["Sci Fi Wall Metallic.003"]}
						position={[49.474, -0.358, 42.952]}
						rotation={[Math.PI, 0, Math.PI]}
						scale={[0.5, 1.648, 1.768]}
					/>
				</group>
				<group name="Node_61">
					<mesh
						name="Mesh_21"
						castShadow
						receiveShadow
						geometry={nodes.Mesh_21.geometry}
						material={materials["Material.142"]}
						position={[234.883, 74.65, 7.954]}
						scale={1.171}
					/>
					<mesh
						name="Mesh_21001"
						castShadow
						receiveShadow
						geometry={nodes.Mesh_21001.geometry}
						material={materials["Material.142"]}
						position={[90.962, 57.807, -18.697]}
						rotation={[-Math.PI, 0.308, -Math.PI]}
						scale={[0.587, 1.415, 0.587]}
					/>
					<mesh
						name="Mesh_21002"
						castShadow
						receiveShadow
						geometry={nodes.Mesh_21002.geometry}
						material={materials["Material.142"]}
						position={[105.625, 57.807, -41.936]}
						rotation={[-Math.PI, 0.852, -Math.PI]}
						scale={[0.587, 1.415, 0.587]}
					/>
					<mesh
						name="Mesh_21003"
						castShadow
						receiveShadow
						geometry={nodes.Mesh_21003.geometry}
						material={materials["Material.142"]}
						position={[106.033, 57.807, 56.471]}
						rotation={[Math.PI, -0.845, Math.PI]}
						scale={[0.587, 1.415, 0.587]}
					/>
					<mesh
						name="Mesh_21004"
						castShadow
						receiveShadow
						geometry={nodes.Mesh_21004.geometry}
						material={materials["Material.142"]}
						position={[90.981, 57.807, 32.961]}
						rotation={[Math.PI, -0.309, Math.PI]}
						scale={[0.587, 1.415, 0.587]}
					/>
				</group>
				<group name="Node_62">
					<mesh
						name="Mesh_22"
						castShadow
						receiveShadow
						geometry={nodes.Mesh_22.geometry}
						material={materials["Material.143"]}
						position={[234.883, 74.65, 7.954]}
						scale={1.171}
					/>
					<mesh
						name="Mesh_22001"
						castShadow
						receiveShadow
						geometry={nodes.Mesh_22001.geometry}
						material={materials["Material.143"]}
						position={[90.962, 57.807, -18.697]}
						rotation={[-Math.PI, 0.308, -Math.PI]}
						scale={[0.587, 1.415, 0.587]}
					/>
					<mesh
						name="Mesh_22002"
						castShadow
						receiveShadow
						geometry={nodes.Mesh_22002.geometry}
						material={materials["Material.143"]}
						position={[105.625, 57.807, -41.936]}
						rotation={[-Math.PI, 0.852, -Math.PI]}
						scale={[0.587, 1.415, 0.587]}
					/>
					<mesh
						name="Mesh_22003"
						castShadow
						receiveShadow
						geometry={nodes.Mesh_22003.geometry}
						material={materials["Material.143"]}
						position={[106.033, 57.807, 56.471]}
						rotation={[Math.PI, -0.845, Math.PI]}
						scale={[0.587, 1.415, 0.587]}
					/>
					<mesh
						name="Mesh_22004"
						castShadow
						receiveShadow
						geometry={nodes.Mesh_22004.geometry}
						material={materials["Material.143"]}
						position={[90.981, 57.807, 32.961]}
						rotation={[Math.PI, -0.309, Math.PI]}
						scale={[0.587, 1.415, 0.587]}
					/>
				</group>
				<group name="Node_63">
					<mesh
						name="Mesh_23"
						castShadow
						receiveShadow
						geometry={nodes.Mesh_23.geometry}
						material={materials["Material.144"]}
						position={[234.883, 74.65, 7.954]}
						scale={1.171}
					/>
					<mesh
						name="Mesh_23001"
						castShadow
						receiveShadow
						geometry={nodes.Mesh_23001.geometry}
						material={materials["Material.144"]}
						position={[90.962, 57.807, -18.697]}
						rotation={[-Math.PI, 0.308, -Math.PI]}
						scale={[0.587, 1.415, 0.587]}
					/>
					<mesh
						name="Mesh_23002"
						castShadow
						receiveShadow
						geometry={nodes.Mesh_23002.geometry}
						material={materials["Material.144"]}
						position={[105.625, 57.807, -41.936]}
						rotation={[-Math.PI, 0.852, -Math.PI]}
						scale={[0.587, 1.415, 0.587]}
					/>
					<mesh
						name="Mesh_23003"
						castShadow
						receiveShadow
						geometry={nodes.Mesh_23003.geometry}
						material={materials["Material.144"]}
						position={[106.033, 57.807, 56.471]}
						rotation={[Math.PI, -0.845, Math.PI]}
						scale={[0.587, 1.415, 0.587]}
					/>
					<mesh
						name="Mesh_23004"
						castShadow
						receiveShadow
						geometry={nodes.Mesh_23004.geometry}
						material={materials["Material.144"]}
						position={[90.981, 57.807, 32.961]}
						rotation={[Math.PI, -0.309, Math.PI]}
						scale={[0.587, 1.415, 0.587]}
					/>
				</group>
				<mesh
					name="Plane002"
					castShadow
					receiveShadow
					geometry={nodes.Plane002.geometry}
					material={materials["Material.136"]}
					position={[-0.283, 20.043, 6.403]}
				/>
				<mesh
					name="Plane003_1"
					castShadow
					receiveShadow
					geometry={nodes.Plane003_1.geometry}
					material={materials["Material.134"]}
					position={[0, 19.771, 8.233]}
				/>
				<mesh
					name="Plane003_2"
					castShadow
					receiveShadow
					geometry={nodes.Plane003_2.geometry}
					material={materials["Inside wall panel of space shuttle.003"]}
					position={[0, 19.771, 8.233]}
				/>
				<mesh
					name="Plane003_3"
					castShadow
					receiveShadow
					geometry={nodes.Plane003_3.geometry}
					material={materials["SciFi Structural Panelling.019"]}
					position={[0, 19.771, 8.233]}
				/>
				<mesh
					name="Plane003_4"
					castShadow
					receiveShadow
					geometry={nodes.Plane003_4.geometry}
					material={materials["Scifi Fabric Panels 01.020"]}
					position={[0, 19.771, 8.233]}
				/>
				<mesh
					name="Plane005"
					castShadow
					receiveShadow
					geometry={nodes.Plane005.geometry}
					material={materials["SciFi Structural Panelling.018"]}
					position={[-0.079, 8.349, -23.172]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<mesh
					name="Plane005_2"
					castShadow
					receiveShadow
					geometry={nodes.Plane005_2.geometry}
					material={materials["Material.137"]}
					position={[195.815, 39.73, 7.755]}
					rotation={[Math.PI / 2, 0, -Math.PI / 2]}
				/>
				<mesh
					name="Plane006_1"
					castShadow
					receiveShadow
					geometry={nodes.Plane006_1.geometry}
					material={materials["PBR fresh gold.006"]}
					position={[175.238, 91.799, -48.656]}
				/>
				<mesh
					name="Plane006_2"
					castShadow
					receiveShadow
					geometry={nodes.Plane006_2.geometry}
					material={materials["Material.138"]}
					position={[175.238, 91.799, -48.656]}
				/>
				<mesh
					name="Plane012"
					castShadow
					receiveShadow
					geometry={nodes.Plane012.geometry}
					material={materials["Material.134"]}
					position={[1.146, 0.632, 11.359]}
				/>
				<mesh
					name="Plane012_1"
					castShadow
					receiveShadow
					geometry={nodes.Plane012_1.geometry}
					material={materials["Material.135"]}
					position={[1.146, 0.632, 11.359]}
				/>
				<mesh
					name="Plane017"
					castShadow
					receiveShadow
					geometry={nodes.Plane017.geometry}
					material={materials["Material.139"]}
					position={[71.312, 0, 7.131]}
					rotation={[Math.PI / 2, 0, -Math.PI / 2]}
					scale={28.291}
				/>
				<mesh
					name="Plane018"
					castShadow
					receiveShadow
					geometry={nodes.Plane018.geometry}
					material={materials["Material.140"]}
					position={[-54.816, 10.204, 22.869]}
					rotation={[Math.PI / 2, 0, -Math.PI / 2]}
					scale={13.656}
				/>
				<mesh
					name="Plane019"
					castShadow
					receiveShadow
					geometry={nodes.Plane019.geometry}
					material={materials["Default.002"]}
					position={[-54.816, 10.204, 22.869]}
					rotation={[Math.PI / 2, 0, -Math.PI / 2]}
					scale={13.656}
				/>
				<mesh
					name="Plane023_1"
					castShadow
					receiveShadow
					geometry={nodes.Plane023_1.geometry}
					material={materials["Material.141"]}
					position={[0, 8.567, -26.536]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={8.295}
				/>
				<mesh
					name="Plane_1"
					castShadow
					receiveShadow
					geometry={nodes.Plane_1.geometry}
					material={materials["Black and Gold Marble Veining.003"]}
					position={[197.751, 41.731, 7.717]}
				/>
				<mesh
					name="Plane_2"
					castShadow
					receiveShadow
					geometry={nodes.Plane_2.geometry}
					material={materials["Material.133"]}
					position={[197.751, 41.731, 7.717]}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("models/capstoneEnvironement-camera.glb");
